---
version: '3.8'

services:
  # logging handled in traefik and authelia
  # does not run as root
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:${VERSION}
    container_name: prowlarr
    restart: unless-stopped
    networks:
      traefik:
        aliases:
          - ${DOMAIN}
    expose:
      - 9696
    environment:
      TZ: ${TIMEZONE}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${DATA_PATH}:/config
    labels:
      traefik.enable: true
      traefik.http.routers.prowlarr.service: prowlarr
      traefik.http.routers.prowlarr.rule: Host(`${DOMAIN}`)
      traefik.http.routers.prowlarr.entrypoints: https
      traefik.http.routers.prowlarr.tls: true
      traefik.http.services.prowlarr.loadbalancer.server.port: 9696
      traefik.http.routers.prowlarr.middlewares: mfa

networks:
  traefik:
    name: traefik
    external: true
