---
- import_tasks: users.yml

- name: Ensure tautulli data directory
  file:
    path: "{{ tautulli_data_path }}"
    owner: "{{ tautulli_user }}"
    group: "{{ tautulli_group }}"
    mode: 0750
    state: directory

- name: Ensure tautulli docker directory
  file:
    path: "{{ tautulli_install_path }}"
    owner: root
    group: root
    mode: 0550
    state: directory

- name: Install tautulli files
  copy:
    src: docker-compose.yml
    dest: "{{ tautulli_install_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0440

- name: Copying template files
  template:
    src: .env.j2
    dest: "{{ tautulli_install_path }}/.env"
    owner: root
    group: root
    mode: 0440

- name: Check if running
  command:
    cmd: docker ps -qf name="tautulli"
  register: this
  changed_when: not this.stdout
  failed_when: false
  notify: restart tautulli
