---
stack:
  name: plex
  ensure_running:
    - plex
  compose_directory: "{{ common_install_root }}/plex"

targets:
  - src: install
    dest: "{{ common_install_root }}/plex"
  - dest: /cache/plex

users:
  - user: plex

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*

  - owner: root
    group: root
    mode: '0550'
    paths:
      - install/set-claim

  - owner: plex
    group: plex
    mode: '0440'
    dir_mode: '0750'
    paths:
      - /cache/plex
