---
- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ restic_schedule_config_path }}/{{ restic_schedule_name }}"
    state: directory
    owner: root
    group: root
    mode: "0750"

- name: Ensure restic systemd service is configured
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0440"
  loop:
    - src: systemd/restic@.service.j2
      dest: "{{ restic_schedule_systemd_path }}/restic@.service"
    - src: systemd/restic.timer.j2
      dest: "{{ restic_schedule_systemd_path }}/restic-{{ restic_schedule_name }}.timer"
    - src: repo.conf.j2
      dest: "{{ restic_schedule_config_path }}/repo.conf"
  loop_control:
    label: "{{ item.src }}"
  notify:
    - Reload systemd
    - Enable timer

- name: Ensure database backup script exists
  ansible.builtin.template:
    src: scripts/restic-backup.j2
    dest: "{{ restic_schedule_install_path }}/restic-backup"
    owner: root
    group: root
    mode: "0550"

- name: Ensure pushover script exists
  ansible.builtin.copy:
    src: pushover
    dest: "{{ restic_schedule_install_path }}/pushover"
    owner: root
    group: root
    mode: "0550"

- name: Ensure include patterns exist
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: "0440"
  loop:
    - src: include.conf.j2
      dest: "{{ restic_schedule_config_path }}/{{ restic_schedule_name }}/include.conf"
    - src: exclude.conf.j2
      dest: "{{ restic_schedule_config_path }}/{{ restic_schedule_name }}/exclude.conf"
    - src: databases.conf.j2
      dest: "{{ restic_schedule_config_path }}/{{ restic_schedule_name }}/databases.conf"
  loop_control:
    label: "{{ item.src }}"

- name: Create symbolic link
  ansible.builtin.file:
    src: "{{ restic_schedule_install_path }}/{{ item }}"
    dest: "{{ restic_schedule_bin_path }}/{{ item }}"
    owner: root
    group: root
    state: link
  loop:
    - restic-backup
    - pushover
  loop_control:
    label: "{{ item }}"
