---
- name: Install user services
  hosts: all
  vars_files:
    - ../../vars/common.yml
    - ../../vars/secrets.yml
  become: true
  gather_facts: false
  roles:
    # https://hub.docker.com/r/bitwardenrs/server/tags
    - role: bitwarden
      bitwarden_fqdn: warden.{{ vault_domain }}
      bitwarden_log_path: /var/log/bitwarden
      bitwarden_data_path: /data/bitwarden
      bitwarden_image_tag: 1.17.0
      bitwarden_signups_allowed: true
      bitwarden_invitations_allowed: true
      bitwarden_admin_token: "{{ vault_bitwarden_admin_token }}"
      bitwarden_smtp_username: "{{ vault_smtp_username }}"
      bitwarden_smtp_password: "{{ vault_smtp_password }}"
      bitwarden_smtp_from: "{{ common_smtp_from }}"
      bitwarden_smtp_server: "{{ common_smtp_server }}"

    # https://hub.docker.com/r/pglombardo/pwpush-ephemeral/tags
    - role: pwpusher
      pwpusher_image_tag: 1.4
      pwpusher_fqdn: fling.{{ vault_domain }}
