---
- name: Install user services
  hosts: all
  vars_files:
    - ../../vars/common.yml
    - ../../vars/secrets.yml
  become: true
  gather_facts: false

  pre_tasks:
    - name: Ensure common data directory exists
      file:
        path: "{{ common_data_root }}"
        owner: root
        group: root
        mode: 0440
        state: directory

  roles:
    # https://hub.docker.com/r/bitwardenrs/server/tags
    - role: bitwarden
      bitwarden_fqdn: warden.{{ vault_domain }}
      bitwarden_log_path: /var/log/bitwarden
      bitwarden_data_path: "{{ common_data_root }}/bitwarden"
      bitwarden_image_tag: 1.17.0
      bitwarden_signups_allowed: true
      bitwarden_invitations_allowed: true
      bitwarden_disable_admin_token: true
      bitwarden_smtp_username: "{{ vault_smtp_username }}"
      bitwarden_smtp_password: "{{ vault_smtp_password }}"
      bitwarden_smtp_from: "{{ common_smtp_from }}"
      bitwarden_smtp_server: "{{ common_smtp_server }}"

    # https://hub.docker.com/r/pglombardo/pwpush-ephemeral/tags
    - role: pwpusher
      pwpusher_image_tag: 1.4
      pwpusher_fqdn: fling.{{ vault_domain }}
