---
stack:
  name: portainer
  ensure_running:
    - portainer
  compose_directory: "{{ common_install_root }}/portainer"

targets:
  - src: install
    dest: "{{ common_install_root }}/portainer"

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*
