---
version: '3.8'

services:
  # does not run as root
  ddclient:
    image: lscr.io/linuxserver/ddclient:${VERSION}
    container_name: ddclient
    restart: unless-stopped
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ./config:/config:ro
