---
- name: Ensure pihole data directory
  file:
    path: "{{ pihole_data_path }}"
    owner: "{{ pihole_user }}"
    group: "{{ pihole_group }}"
    mode: 0775
    state: directory

- name: Ensure pihole install directory
  file:
    path: "{{ pihole_install_path }}"
    owner: root
    group: root
    mode: 0750
    state: directory

- name: Ensure pihole fix directory
  file:
    path: "{{ pihole_install_path }}/fix"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Ensure pihole config directory
  file:
    path: "{{ pihole_install_path }}/config"
    owner: root
    group: root
    mode: 0750
    state: directory

- name: Ensure dhcp relay directory
  file:
    path: "{{ pihole_install_path }}/dhcp_helper"
    owner: root
    group: root
    mode: 0750
    state: directory
