---
- name: Ensure common data directory exists
  file:
    path: "{{ common_data_root }}"
    owner: root
    group: root
    mode: 0440
    state: directory

- name: Ensure common download directory exists
  file:
    path: "{{ common_downloads_root }}"
    owner: "{{ common_downloads_user }}"
    group: "{{ common_downloads_group }}"
    mode: 0550
    state: directory

- name: Ensure common install directory
  file:
    path: "{{ common_install_root }}"
    owner: root
    group: root
    mode: 0550
    state: directory

- name: Ensure common log directory exists
  file:
    path: "{{ common_logs_root }}"
    owner: root
    group: root
    mode: 0440
    state: directory
