---
- name: Add group {{ common_downloads_group }}
  group:
    name: "{{ common_downloads_group }}"
    state: present

- name: Add user {{ common_downloads_user }}
  user:
    name: "{{ common_downloads_user }}"
    group: "{{ common_downloads_group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present

- import_tasks: directories.yml

- name: Install management script
  template:
    src: manage.sh
    dest: /usr/sbin/{{ common_script_name }}
    owner: root
    group: root
    mode: 0550
