---
- name: Install downloaders
  hosts: all
  vars_files:
    - ../../vars/common.yml
    - ../../vars/secrets.yml
  become: true
  gather_facts: false

  roles:
    # https://github.com/linuxserver/docker-nzbget/releases
    - role: nzbget
      nzbget_fqdn: newz.{{ vault_domain }}
      nzbget_image_tag: v21.1-ls87
      nzbget_data_path: "{{ common_data_root }}/nzbget"
      nzbget_downloads_path: "{{ common_downloads_root }}/nzb"
      nzbget_software_root: "{{ common_software_root }}"
      nzbget_install_path: "{{ common_install_root }}/nzbget"
      nzbget_user: "{{ common_downloads_user }}"
      nzbget_group: "{{ common_downloads_group }}"

    # https://github.com/linuxserver/docker-deluge/releases
    - role: deluge
      deluge_image_tag: 2.0.3-2201906121747ubuntu18.04.1-ls116
      deluge_fqdn: bt.{{ vault_domain }}
      deluge_data_path: "{{ common_data_root }}/deluge"
      deluge_downloads_path: "{{ common_downloads_root }}/torrent"
      deluge_software_root: "{{ common_software_root }}"
      pia_username: "{{ vault_pia_username }}"
      pia_password: "{{ vault_pia_password }}"
      deluge_install_path: "{{ common_install_root }}/deluge"
      deluge_user: "{{ common_downloads_user }}"
      deluge_group: "{{ common_downloads_group }}"
