---
stack:
  name: elasticsearch
  ensure_running:
    - elasticsearch
  compose_directory: "{{ common_install_root }}/elasticsearch"

targets:
  - src: install
    dest: "{{ common_install_root }}/elasticsearch"

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*

  - owner: root
    group: root
    mode: '0660'
    dir_mode: '0555'
    paths:
      - config
      - config/*
