---
targets:
  - src: install
    dest: "{{ common_install_root }}/ombi"
  - dest: "{{ common_data_root }}/ombi"

users:
  ombi: []

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*

  - owner: ombi
    group: ombi
    dir_mode: '0750'
    paths:
      - "{{ common_data_root }}/ombi"
