---
- name: Ensure hydra docker directory
  file:
    path: "{{ hydra_install_path }}"
    owner: root
    group: root
    mode: 0550
    state: directory

- name: Ensure hydra data directory
  file:
    path: "{{ hydra_data_path }}"
    owner: "{{ hydra_user }}"
    group: "{{ hydra_group }}"
    mode: 0750
    state: directory

# - name: Ensure hydra torrent drop directory
#   file:
#     path: "{{ hydra_torrent_drop_path }}"
#     owner: "{{ hydra_user }}"
#     group: "{{ hydra_group }}"
#     mode: 0750
#     state: directory
