---
stack:
  name: prowlarr
  ensure_running:
    - prowlarr
  compose_directory: "{{ common_install_root }}/prowlarr"

targets:
  - src: install
    dest: "{{ common_install_root }}/prowlarr"
  - dest: "{{ common_data_root }}/prowlarr"

users:
  - user: prowlarr

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*

  - owner: prowlarr
    group: prowlarr
    mode: '0440'
    dir_mode: '0750'
    paths:
      - "{{ common_data_root }}/prowlarr"
