---
- name: Add jackett group {{ jackett_group }}
  group:
    name: "{{ jackett_group }}"
    state: present

- name: Add jackett user {{ jackett_user }}
  user:
    name: "{{ jackett_user }}"
    group: "{{ jackett_group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present

- name: Export {{ jackett_group }} group id
  getent:
    database: group
    key: "{{ jackett_group }}"

- name: Export {{ jackett_user }} user id
  getent:
    database: passwd
    key: "{{ jackett_user }}"

- name: Gather created username and group IDs
  set_fact:
    jackett_user_id: "{{ getent_passwd[jackett_user][1] }}"
    jackett_group_id: "{{ getent_group[jackett_group][1] }}"
