---
- name: Add group {{ authelia_group }}
  group:
    name: "{{ authelia_group }}"
    state: present

- name: Add user {{ authelia_user }}
  user:
    name: "{{ authelia_user }}"
    group: "{{ authelia_group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present

- name: Export {{ authelia_group }} group id
  getent:
    database: group
    key: "{{ authelia_group }}"

- name: Export {{ authelia_user }} user id
  getent:
    database: passwd
    key: "{{ authelia_user }}"

- name: Gather created user and group ID
  set_fact:
    authelia_user_id: "{{ getent_passwd[authelia_user][1] }}"
    authelia_group_id: "{{ getent_group[authelia_group][1] }}"
