---
- name: Ensure elasticsearch install directory
  file:
    path: "{{ elasticsearch_install_path }}"
    owner: root
    group: root
    mode: 0550
    state: directory

- name: Ensure elasticsearch config directory
  file:
    path: "{{ elasticsearch_install_path }}/config"
    owner: root
    group: root
    mode: 0555
    state: directory
