---
stack:
  name: pwpusher
  ensure_running:
    - pwpusher
  compose_directory: "{{ common_install_root }}/pwpusher"
  force_pull: true

targets:
  - src: install
    dest: "{{ common_install_root }}/pwpusher"

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*
