---
jackett_fqdn: jackett.local
jackett_image_tag: latest
jackett_timezone: America/Los_Angeles

jackett_install_path: /opt/jackett
jackett_data_path: /data/jackett

jackett_user: jackett
jackett_group: jackett
