---
stack:
  name: whisparr
  ensure_running:
    - whisparr
  compose_directory: "{{ common_install_root }}/whisparr"
  # force_pull: true

targets:
  - src: install
    dest: "{{ common_install_root }}/whisparr"
  - dest: "{{ common_data_root }}/whisparr"

users:
  - user: "{{ common_downloads_user }}"
    group: "{{ common_downloads_group }}"

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*

  - owner: "{{ common_downloads_user }}"
    group: "{{ common_downloads_group }}"
    mode: '0440'
    # whisparr will override what you put here
    dir_mode: '0775'
    paths:
      - "{{ common_data_root }}/whisparr"
