---
- name: Remove old docker packages
  ansible.builtin.apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Ensure keyrings directory exists
  ansible.builtin.file:
    path: "/etc/apt/keyrings"
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Add repo key and source
  block:
    - name: Docker repo key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.asc
        owner: root
        group: root
        mode: "0644"

    - name: Docker repo apt source
      ansible.builtin.apt_repository:
        filename: docker
        repo: >-
          deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc]
          https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        update_cache: false
        state: present

- name: Install docker and required packages
  ansible.builtin.apt:
    update_cache: true
    name:
      - docker-ce{{ docker_package }}
      - docker-ce-cli{{ docker_package }}
      - containerd.io{{ docker_containerd_package }}
      - docker-buildx-plugin{{ docker_buildx_package }}
      - docker-compose-plugin{{ docker_compose_package }}
      - python3-docker
    state: present
  register: docker_install

- name: Start docker service
  ansible.builtin.systemd:
    name: docker
    enabled: true
    state: started

- name: Handle networks and volumes
  ansible.builtin.import_tasks: extras.yml
