---
- name: Add Debian/Ubuntu Docker Repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/\
      {{ ansible_distribution|lower }} {{ ansible_distribution_release }} \
      stable"
    filename: docker
    state: present

- name: Remove old docker packages
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Install docker
  package:
    name:
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version }}
      - containerd.io={{ docker_containerd_version }}
    state: present
  register: docker_install

- name: Start docker service
  systemd:
    name: docker
    enabled: true
    state: started

- import_tasks: extras.yml

- import_tasks: compose.yml
