---
- name: Remove old docker packages
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Ensure keyrings directory exists
  file:
    path: "/etc/apt/keyrings"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Add repo key and source
  block:
    - name: docker repo key
      get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /etc/apt/keyrings/docker.gpg

    - name: docker repo apt source
      apt_repository:
        # signed-by=/etc/apt/keyrings/docker.gpg
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        state: present

- name: Install docker and required packages
  apt:
    update_cache: true
    name:
      - docker-ce={{ docker_version }}
      - docker-ce-cli={{ docker_version }}
      - containerd.io={{ docker_containerd_version }}
      - docker-buildx-plugin={{ docker_buildx_version }}
      - docker-compose-plugin={{ docker_compose_version }}
      - python3-pip
    state: present
  register: docker_install

- name: Ensure required python modules are installed
  pip:
    name: docker

- name: Start docker service
  systemd:
    name: docker
    enabled: true
    state: started

- import_tasks: extras.yml
