---
- name: Unload nouveau
  modprobe:
    name: nouveau
    state: absent
  ignore_errors: true

# TODO: check if nvidia persistence mode is necessary

- name: Ensure latest nvidia driver
  package:
    name: nvidia-headless-{{ nvidia_driver_version }}
    state: present

- name: Add nvidia repository GPG key [Debian/Ubuntu]
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present
  when: ansible_distribution|lower in ['ubuntu', 'debian']

- name: Add nvidia repository GPG key [CentOS/Fedora/Red Hat]
  rpm_key:
    key: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present
  when: ansible_distribution|lower in ['centos', 'fedora', 'rhel']

- name: Add nvidia repository
  get_url:
    url: "https://nvidia.github.io/nvidia-docker/\
      {{ ansible_distribution | lower }}\
      {{ ansible_distribution_version }}/nvidia-docker.list"
    dest: /etc/apt/sources.list.d/nvidia-docker.list
  register: nvidia_repo

- name: Update apt
  apt:
    update_cache: true
  when: >
    ansible_distribution|lower in ['debian', 'ubuntu'] and
    nvidia_repo.changed

- name: Install nvidia container packages
  package:
    name:
      - nvidia-docker2
      - nvidia-container-toolkit
    state: present
  notify:
    - restart docker
