---
- name: Ensure portainer docker directory
  file:
    path: "{{ portainer_install_path }}"
    owner: root
    group: root
    mode: 0550
    state: directory

- name: Copy portainer files
  copy:
    src: docker-compose.yml
    dest: "{{ portainer_install_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0440
  notify:
    - restart portainer

- name: Copy portainer templates
  template:
    src: .env.j2
    dest: "{{ portainer_install_path }}/.env"
    owner: root
    group: root
    mode: 0440
  notify:
    - restart portainer

- name: Check for latest
  command:
    cmd: echo 'pull latest docker image'
  when: portainer_image_tag == 'latest'
  notify: restart portainer

- name: Check if running
  command:
    cmd: docker ps -qf name="portainer"
  register: this
  changed_when: not this.stdout
  failed_when: false
  notify: restart portainer
