---
- name: Ensure software root directory
  stat:
    path: "{{ deluge_software_root }}"
  register: this
  changed_when: false
  failed_when: false

- name: fail check
  fail:
    msg: The software root directory '{{ deluge_software_root }}' must exist
  when: this.stat.isdir is undefined or not this.stat.isdir

- name: Ensure deluge data directory
  file:
    path: "{{ deluge_data_path }}"
    owner: "{{ deluge_user }}"
    group: "{{ deluge_group }}"
    mode: 0750
    state: directory

- name: Ensure deluge install directory
  file:
    path: "{{ deluge_install_path }}"
    owner: root
    group: root
    mode: 0550
    state: directory

- name: Ensure deluge wait-for-vpn directory
  file:
    path: "{{ deluge_install_path }}/wait"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Ensure download directory
  file:
    path: "{{ deluge_downloads_path }}"
    owner: "{{ deluge_user }}"
    group: "{{ deluge_group }}"
    mode: 0770
    state: directory

# - name: Ensure download directory
#   file:
#     path: "{{ deluge_downloads_path }}"
#     owner: "{{ deluge_downloads_user }}"
#     group: "{{ deluge_downloads_group }}"
#     mode: 0770
#     state: directory
