---
- name: Add group {{ deluge_group }}
  group:
    name: "{{ deluge_group }}"
    state: present

- name: Add user {{ deluge_user }}
  user:
    name: "{{ deluge_user }}"
    group: "{{ deluge_group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present

- name: Export group id
  getent:
    database: group
    key: "{{ deluge_group }}"

- name: Export user id
  getent:
    database: passwd
    key: "{{ deluge_user }}"

- name: Gather created username and group IDs
  set_fact:
    deluge_user_id: "{{ getent_passwd[deluge_user][1] }}"
    deluge_group_id: "{{ getent_group[deluge_group][1] }}"
