---
bitwarden_user: bitwarden
bitwarden_group: bitwarden
bitwarden_fqdn: warden.local
bitwarden_log_level: info

bitwarden_log_path: /var/log/bitwarden
bitwarden_install_path: /opt/bitwarden
bitwarden_data_path: /data/bitwarden

bitwarden_image_tag: latest

bitwarden_signups_allowed: true
bitwarden_invitations_allowed: true
bitwarden_show_password_hint: false

bitwarden_admin_token:
bitwarden_smtp_username:
bitwarden_smtp_password:
bitwarden_smtp_port: 587
bitwarden_smtp_ssl: true
bitwarden_smtp_from:
bitwarden_smtp_server:
