---
- name: Ensure user group exist.
  ansible.builtin.group:
    name: "{{ overseerr_group }}"
    state: present

- name: Ensure service users exist.
  ansible.builtin.user:
    name: "{{ overseerr_user }}"
    group: "{{ overseerr_group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present

- name: Export group IDs
  ansible.builtin.getent:
    database: group
    key: "{{ overseerr_group }}"
  changed_when: false
  register: getent_groups

- name: Export user IDs
  ansible.builtin.getent:
    database: passwd
    key: "{{ overseerr_user }}"
  changed_when: false
  register: getent_users

- name: Gather user facts
  ansible.builtin.set_fact:
    overseerr_user_id: "{{ getent_passwd[overseerr_user][1] }}"
    overseerr_group_id: "{{ getent_group[overseerr_group][1] }}"
