---
- name: Ensure sabnzb docker directory
  file:
    path: "{{ sabnzb_install_path }}"
    owner: root
    group: root
    mode: 0550
    state: directory

- name: Ensure sabnzb data directory
  file:
    path: "{{ sabnzb_data_path }}"
    owner: "{{ sabnzb_user }}"
    group: "{{ sabnzb_group }}"
    mode: 0750
    state: directory

- name: Ensure sabnzb downloads directory
  file:
    path: "{{ sabnzb_downloads_path }}"
    owner: "{{ sabnzb_user }}"
    group: "{{ sabnzb_group }}"
    mode: 0770
    state: directory

- name: Ensure sabnzb downloads directory
  file:
    path: "{{ sabnzb_incomplete_path }}"
    owner: "{{ sabnzb_user }}"
    group: "{{ sabnzb_group }}"
    mode: 0770
    state: directory
