---
version: "3.8"

services:
  # logging handled by traefik
  # does not run as root
  pwpusher:
    image: pglombardo/pwpush-ephemeral:${VERSION}
    container_name: pwpusher
    restart: unless-stopped
    init: true
    networks:
      - pusher
    expose:
      - 5000
    labels:
      traefik.enable: true
      traefik.http.routers.fling.service: fling
      traefik.http.routers.fling.rule: Host(`${DOMAIN}`)
      traefik.http.routers.fling.entrypoints: https
      traefik.http.routers.fling.tls: true
      traefik.http.services.fling.loadbalancer.server.port: 5000

networks:
  pusher:
    name: pusher
    external: true
