---
- name: Add group {{ traefik_group }}
  group:
    name: "{{ traefik_group }}"
    state: present

- name: Add user {{ traefik_user }}
  user:
    name: "{{ traefik_user }}"
    group: "{{ traefik_group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present

- name: Export {{ traefik_group }} group id
  getent:
    database: group
    key: "{{ traefik_group }}"

- name: Export {{ traefik_user }} user id
  getent:
    database: passwd
    key: "{{ traefik_user }}"

- name: Gather created user and group IDs
  set_fact:
    traefik_user_id: "{{ getent_passwd[traefik_user][1] }}"
    traefik_group_id: "{{ getent_group[traefik_group][1] }}"
