---
targets:
  - src: install
    dest: "{{ common_install_root }}/deluge"
  - dest: "{{ common_data_root }}/deluge"
  - dest: "{{ common_downloads_root }}/torrent"

users:
  - user: "{{ common_downloads_user }}"
    group: "{{ common_downloads_group }}"

permissions:
  - owner: root
    group: root
    mode: '0755'
    dir_mode: '0755'
    paths:
      - install/wait
      - install/wait/*

  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*

  - owner: "{{ common_downloads_user }}"
    group: "{{ common_downloads_group }}"
    mode: '0440'
    dir_mode: '0750'
    paths:
      - "{{ common_data_root }}/deluge"

  - owner: "{{ common_downloads_user }}"
    group: "{{ common_downloads_group }}"
    mode: '0440'
    dir_mode: '0770'
    paths:
      - "{{ common_downloads_root }}/torrent"

