---
stack:
  name: deluge
  ensure_running:
    - deluge
    - gluetun
  compose_directory: "{{ common_install_root }}/deluge"
  # force_pull: true

targets:
  - src: install
    dest: "{{ common_install_root }}/deluge"
  - dest: "{{ common_data_root }}/deluge"
  - dest: "{{ common_downloads_root }}/torrent"
  - dest: "{{ deluge.gluetun_config_full_path }}"

users:
  - user: "{{ common_downloads_user }}"
    group: "{{ common_downloads_group }}"

permissions:
  - owner: root
    group: root
    mode: '0550'
    dir_mode: '0755'
    paths:
      - install/wait
      - install/wait/*

  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*

  - owner: root
    group: root
    mode: '0640'
    dir_mode: '0750'
    paths:
      - "{{ deluge.gluetun_config_path }}"
      - "{{ deluge.gluetun_config_path }}/*"

  - owner: "{{ common_downloads_user }}"
    group: "{{ common_downloads_group }}"
    mode: '0440'
    dir_mode: '0750'
    paths:
      - "{{ common_data_root }}/deluge"

  - owner: "{{ common_downloads_user }}"
    group: "{{ common_downloads_group }}"
    mode: '0440'
    dir_mode: '0770'
    paths:
      - "{{ common_downloads_root }}/torrent"
