---
- name: Ensure static data directory
  file:
    path: "{{ static_data_path }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: Ensure static docker directory
  file:
    path: "{{ static_install_path }}"
    owner: root
    group: root
    mode: 0550
    state: directory

- name: Install static files
  copy:
    src: "{{ item }}"
    dest: "{{ static_install_path }}/{{ item }}"
    owner: root
    group: root
    mode: 0440
  loop:
    - docker-compose.yml
    - default.conf
  notify: restart static

- name: Install robots.txt
  copy:
    src: robots.txt
    dest: "{{ static_data_path }}/robots.txt"
    owner: root
    group: root
    mode: 0444

- name: Copying template files
  template:
    src: .env.j2
    dest: "{{ static_install_path }}/.env"
    owner: root
    group: root
    mode: 0440
  notify: restart static

- name: Check if running
  command:
    cmd: docker ps -qf name="static"
  register: this
  changed_when: not this.stdout
  failed_when: false
  notify: restart static
