---
- name: Add hydra group {{ hydra_group }}
  group:
    name: "{{ hydra_group }}"
    state: present

- name: Add hydra user {{ hydra_user }}
  user:
    name: "{{ hydra_user }}"
    group: "{{ hydra_group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present

- name: Export {{ hydra_group }} group id
  getent:
    database: group
    key: "{{ hydra_group }}"

- name: Export {{ hydra_user }} user id
  getent:
    database: passwd
    key: "{{ hydra_user }}"

- name: Gather created username and group IDs
  set_fact:
    hydra_user_id: "{{ getent_passwd[hydra_user][1] }}"
    hydra_group_id: "{{ getent_group[hydra_group][1] }}"
