#!/bin/bash

set -o errexit
set -o nounset
set -o pipefail

plexLogin()
{
  declare username="${1}" password="${2}"

  local result=$(curl -s --header "X-Plex-Client-Identifier: Nateflix" \
          --header "X-Plex-Product: Plex SSO" \
          --header "X-Plex-Version: V1" \
          -d "user[login]=${username}&user[password]=${password}" \
          -X POST https://plex.tv/users/sign_in.json)

  local re="^\{\"error\":\"(.+)\"\}$"
  if [[ $result =~ $re ]]; then
    echo "Login failed: ${BASH_REMATCH[1]}" 1>&2
    return 1
  elif [[ ${result} != *"{\"user\":"* ]]; then
    echo "Login failed: Unexpected result, try again later" 1>&2
    echo "${result}" 1>&2
    return 1
  else
    token=$(echo ${result} | grep -ioe '"authToken":"[^"]*' | cut -c 14-)
    if [[ -z ${token} ]]; then
      echo "Unable to parse plex login token" 1>&2
      return 1
    fi
  fi

  echo "${token}"
}

getPlexClaim()
{
  declare loginToken="${1}"

  local result=$(curl -s --header "X-Plex-Client-Identifier: Nateflix" \
          --header "X-Plex-Product: Plex SSO" \
          --header "X-Plex-Token: ${loginToken}" \
          -X GET https://plex.tv/api/claim/token.json)

  claim=$(echo ${result} | grep -ioe '"token":"[^"]*' | cut -c 10-)
  if [[ -z ${claim} ]]; then
    echo "Error retrieving Plex Claim Token" 1>&2
    echo ${result} 1>&2
    return 1
  fi

  echo ${claim}
}

while [[ -z ${plexUsername:-} || -z ${plexPassword:-} && -z ${plexToken:-} ]]; do
  read -ep "Plex username: " plexUsername
  read -esp "Plex password: " plexPassword
  echo
  if [[ -z ${plexUsername} || -z ${plexPassword} ]]; then
    echo "Plex username and password required"
  elif [[ -n ${plexUsername} && -n ${plexPassword} ]]; then
    plexToken=$(plexLogin "${plexUsername}" "${plexPassword}")
  fi
done

echo "Getting plex server claim token"
claim=$(getPlexClaim "${plexToken}")

if [[ ! -f ./.env ]]; then
  echo "No .env file found"
  echo "claim: ${claim}"
  exit 0
fi

echo "Setting plex claim in environment file, restart plex container"
echo "This token will be valid for only 4 minutes"
sed -i -e "s/^PLEX_CLAIM=.*\$/PLEX_CLAIM=${claim}/g" ./.env
