---
version: '3.8'

services:
  # logging handled in traefik and authelia
  # does not run as root
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:${VERSION}
    container_name: sabnzbd
    restart: unless-stopped
    networks:
      traefik:
        aliases:
          - ${DOMAIN}
    expose:
      - 8080
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - source: software-mount
        type: volume
        target: /data
        volume:
          nocopy: true
      - ${DATA_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${INCOMPLETE_DOWNLOADS}:/incomplete-downloads
    labels:
      traefik.enable: true
      traefik.http.routers.sabnzbd.service: sabnzbd
      traefik.http.routers.sabnzbd.rule: Host(`${DOMAIN}`)
      traefik.http.routers.sabnzbd.entrypoints: https
      traefik.http.routers.sabnzbd.tls: true
      traefik.http.services.sabnzbd.loadbalancer.server.port: 8080
      traefik.http.routers.sabnzbd.middlewares: mfa


volumes:
  software-mount:
    name: software-mount
    external: true

networks:
  traefik:
    name: traefik
    external: true
