---
- name: Ensure user group exist.
  ansible.builtin.group:
    name: "{{ tautulli_group }}"
    state: present

- name: Ensure service users exist.
  ansible.builtin.user:
    name: "{{ tautulli_user }}"
    group: "{{ tautulli_group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present

- name: Export group IDs
  ansible.builtin.getent:
    database: group
    key: "{{ tautulli_group }}"
  changed_when: false
  register: getent_groups

- name: Export user IDs
  ansible.builtin.getent:
    database: passwd
    key: "{{ tautulli_user }}"
  changed_when: false
  register: getent_users

- name: Gather user facts
  ansible.builtin.set_fact:
    tautulli_user_id: "{{ getent_passwd[tautulli_user][1] }}"
    tautulli_group_id: "{{ getent_group[tautulli_group][1] }}"
