---
services:
  postfix:
    image: juanluisbaptiste/postfix:${VERSION}
    init: true
    container_name: postfix
    restart: always
    networks:
      - traefik
    ports:
      - 2525:25/tcp
    expose:
      - 25
    environment:
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      SERVER_HOSTNAME: ${DOMAIN}


networks:
  traefik:
    name: traefik
    external: true
