---
- name: Creating container data directory
  file:
    path: "{{ compose_data_path }}"
    owner: "{{ compose_username }}"
    group: "{{ compose_group }}"
    mode: 0750
    state: directory
  when: compose_data_path

- name: Creating container log directory
  file:
    path: "{{ compose_log_path }}"
    owner: "{{ compose_username }}"
    group: "{{ compose_group }}"
    mode: 0750
    state: directory
  when: compose_log_path

- name: Ensure container docker directory
  file:
    path: "{{ compose_path }}"
    owner: root
    group: root
    mode: 0550
    state: directory
