---
- name: Checking for extra groups
  getent:
    database: group
    key: "{{ item }}"
  loop: "{{ compose_additional_groups }}"
  register: extra_ids
  when: compose_additional_groups | length > 0
  failed_when: false

- name: Adding new extra groups
  group:
    name: "{{ item.item }}"
    state: present
  loop: "{{ extra_ids.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: "'ansible_facts' not in item"

- name: Adding group {{ compose_group }}
  group:
    name: "{{ compose_group }}"
    state: present
  when: compose_group != 'root'

- name: Adding user {{ compose_username }}
  user:
    name: "{{ compose_username }}"
    group: "{{ compose_username }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present
  when: compose_username != 'root'

- name: Adding {{ compose_username }} to additional groups
  user:
    name: "{{ compose_username }}"
    groups: "{{ compose_additional_groups }}"
    append: true
    state: present
  when: compose_additional_groups | length > 0

- name: Exporting group id
  getent:
    database: group
    key: "{{ compose_group }}"
  changed_when: false

- name: Exporting user id
  getent:
    database: passwd
    key: "{{ compose_username }}"
  changed_when: false

- name: Gather created username and group IDs
  set_fact:
    compose_user_id: "{{ getent_passwd[compose_username][1] }}"
    compose_group_id: "{{ getent_group[compose_group][1] }}"
  changed_when: false
