---
version: '3.8'

services:
  # runs as root, needed for iptables
  fail2ban:
    image: crazymax/fail2ban:${VERSION}
    container_name: fail2ban
    restart: unless-stopped
    init: true
    privileged: true
    cap_add:
      - NET_ADMIN
      - NET_RAW
    network_mode: host
    environment:
      F2B_DB_PURGE_AGE: ${PURGE_AGE}
      F2B_LOG_TARGET: /logs/fail2ban.log
      F2B_LOG_LEVEL: ${LOG_LEVEL}
      SSMTP_HOST: ${SMTP_SERVER}
      SSMTP_PORT: ${SMTP_PORT}
      SSMTP_HOSTNAME: ${SMTP_DOMAIN}
      # SSMTP_USER: ${SMTP_USER}
      # SSMTP_PASSWORD: ${SMTP_PASSWORD}
      SSMTP_TLS: ${SMTP_TLS}
      SSMTP_STARTTLS: ${SMTP_STARTTLS}
    volumes:
      - ${DATA_PATH}/:/data/db/
      - ${INGEST_PATH}/:/ingest/:ro
      - ${LOG_PATH}/:/logs/
      - ./config/action.d/:/data/action.d/:ro
      - ./config/filter.d/:/data/filter.d/:ro
      - ./config/jail.d/:/data/jail.d/:ro
