---
- name: Install and configure required infra
  hosts: all
  vars_files:
    - ../../vars/common.yml
    - ../../vars/secrets.yml
  become: true
  gather_facts: false

  roles:
    - role: networks
      network_names:
        - traefik
        - pusher

    # https://github.com/linuxserver/docker-ddclient/releases
    - role: ddclient
      ddclient_domain: "{{ vault_domain }}"
      ddclient_image_tag: v3.9.1-ls44
      ddclient_cloudflare_username: "{{ vault_admin_email }}"
      ddclient_cloudflare_api_key: "{{ vault_cloudflare_api_key }}"
      ddclient_opendns_username: "{{ vault_opendns_username }}"
      ddclient_opendns_password: "{{ vault_opendns_password }}"
      ddclient_install_path: "{{ common_install_root }}/ddclient"

    # https://hub.docker.com/_/traefik?tab=tags
    - role: traefik
      traefik_domain: "{{ vault_domain }}"
      traefik_image_tag: v2.3.2
      traefik_ssl_cert_path: "{{ common_data_root }}/traefik"
      traefik_log_path: "{{ common_logs_root }}/traefik"
      traefik_allowed_networks: "{{ proxy_internal_only_networks }}"
      traefik_cloudflare_email: "{{ vault_admin_email }}"
      traefik_cloudflare_api_key: "{{ vault_cloudflare_api_key }}"
      traefik_install_path: "{{ common_install_root }}/traefik"

    # https://hub.docker.com/r/pihole/pihole/tags
    - role: pihole
      pihole_data_path: "{{ common_data_root }}/pihole"
      pihole_image_tag: v5.1.2
      pihole_advertise_ip: "{{ advertise_ip }}"
      pihole_domain: "{{ vault_domain }}"
      pihole_upstream_dns: 208.67.222.222
      pihole_install_path: "{{ common_install_root }}/pihole"
