---
- name: Ensure user group exist.
  ansible.builtin.group:
    name: "{{ authelia_group }}"
    state: present

- name: Ensure service users exist.
  ansible.builtin.user:
    name: "{{ authelia_user }}"
    group: "{{ authelia_group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present

- name: Export group IDs
  ansible.builtin.getent:
    database: group
    key: "{{ authelia_group }}"
  changed_when: false
  register: getent_groups

- name: Export user IDs
  ansible.builtin.getent:
    database: passwd
    key: "{{ authelia_user }}"
  changed_when: false
  register: getent_users

- name: Gather user facts
  ansible.builtin.set_fact:
    authelia_user_id: "{{ getent_passwd[authelia_user][1] }}"
    authelia_group_id: "{{ getent_group[authelia_group][1] }}"
