---
- name: Ensure Users and Groups exist.
  ansible.builtin.import_tasks:
    file: users.yml

- name: Ensure required directories exist.
  ansible.builtin.import_tasks:
    file: directories.yml

- name: Ensure required files exist.
  ansible.builtin.import_tasks:
    file: copy_files.yml

- name: Force pull image.
  ansible.builtin.command:
    cmd: echo 'pull latest docker image'
  when: "'latest' in [traefik_tag, traefik_dockerproxy_tag] or traefik_force_pull"
  notify: Restart Traefik

- name: Check if Traefik running.
  ansible.builtin.command:
    cmd: docker ps -qf name=traefik
  register: this
  changed_when: not this.stdout
  failed_when: false
  when: traefik_ensure_running
  notify: Restart Traefik

- name: Check if dockerproxy running.
  ansible.builtin.command:
    cmd: docker ps -qf name=dockerproxy
  register: this
  changed_when: not this.stdout
  failed_when: false
  when: traefik_ensure_running
  notify: Restart Traefik
