---
targets:
  - src: install
    dest: "{{ common_install_root }}/overseerr"
  - dest: "{{ common_data_root }}/overseerr"

users:
  - user: overseerr

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*

  - owner: overseerr
    group: overseerr
    mode: '0440'
    dir_mode: '0750'
    paths:
      - "{{ common_data_root }}/overseerr"
