---
targets:
  - src: install
    dest: "{{ common_install_root }}/postfix"

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0440'
    paths:
      - install
      - install/*
