---
- import_tasks: users.yml

- import_tasks: directories.yml

- name: Copy pihole files
  copy:
    src: "{{ item }}"
    dest: "{{ pihole_install_path }}/{{ item }}"
    owner: root
    group: root
    mode: 0440
  loop:
    - dhcp_helper/Dockerfile
    - docker-compose.yml
  notify:
    - restart pihole

- name: Copy pihole permissions fix
  copy:
    src: fix/30-permissions.sh
    dest: "{{ pihole_install_path }}/fix/30-permissions.sh"
    owner: root
    group: root
    mode: 0755
  notify:
    - restart pihole

- name: Copying environment file
  template:
    src: .env.j2
    dest: "{{ pihole_install_path }}/.env"
    owner: root
    group: root
    mode: 0440
  notify:
    - restart pihole

- name: Copying custom dns files
  template:
    src: config/{{ item.src }}
    dest: "{{ pihole_install_path }}/config/{{ item.dest }}"
    owner: "{{ pihole_user }}"
    group: "{{ pihole_group }}"
    mode: 0444
  loop:
    - src: 02-custom.conf.j2
      dest: 02-custom.conf
    - src: 07-dhcp-options.conf.j2
      dest: 07-dhcp-options.conf
  notify:
    - restart pihole

- name: Check for latest
  command:
    cmd: echo 'pull latest docker image'
  when: pihole_image_tag == 'latest'
  notify: restart pihole

- name: Check if running
  command:
    cmd: docker ps -qf name="pihole"
  register: this
  changed_when: not this.stdout
  failed_when: false
  notify: restart pihole

- name: Create cron job for auto update
  cron:
    name: "pihole update"
    minute: "0"
    hour: "11"
    user: root
    job: /usr/bin/docker exec pihole pihole -g >/var/log/pihole-update.log 2>&1
  when: pihole_auto_update
