---
- name: Add pihole groups
  group:
    name: "{{ item }}"
    state: present
  loop:
    - "{{ pihole_web_group }}"
    - "{{ pihole_group }}"

- name: Add pihole users
  user:
    name: "{{ item.user }}"
    group: "{{ item.group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present
  loop:
    - user: "{{ pihole_web_user }}"
      group: "{{ pihole_web_group }}"
    - user: "{{ pihole_user }}"
      group: "{{ pihole_group }}"

- name: Add {{ pihole_web_user }} to {{ pihole_group }} group
  user:
    name: "{{ pihole_web_user }}"
    groups: "{{ pihole_group }}"
    append: true
    state: present

- name: Export groups
  getent:
    database: group
    key: "{{ item }}"
  register: pihole_groups
  loop:
    - "{{ pihole_web_group }}"
    - "{{ pihole_group }}"

- name: Export users
  getent:
    database: passwd
    key: "{{ item }}"
  register: pihole_users
  loop:
    - "{{ pihole_web_user }}"
    - "{{ pihole_user }}"

- name: Gather created user and group IDs
  set_fact:
    pihole_web_user_id: "{{ pihole_users.results[0].ansible_facts.\
      getent_passwd[pihole_web_user][1] }}"
    pihole_web_group_id: "{{ pihole_groups.results[0].ansible_facts.\
      getent_group[pihole_web_group][1] }}"
    pihole_user_id: "{{ pihole_users.results[1].ansible_facts.\
      getent_passwd[pihole_user][1] }}"
    pihole_group_id: "{{ pihole_groups.results[1].ansible_facts.\
      getent_group[pihole_group][1] }}"
