---
authelia_domain: local
authelia_fqdn: auth.{{ authelia_domain }}
authelia_install_path: /opt/authelia
authelia_log_path: /var/log/authelia
authelia_data_path: /data/authelia
authelia_image_tag: latest

authelia_user: authelia
authelia_group: authelia

authelia_timezone: America/Los_Angeles

authelia_totp_issuer: authelia
authelia_log_level: info
authelia_default_redirection_url: "{{ authelia_domain }}"
authelia_session_cookie: authelia_session
authelia_smtp_server:
authelia_smtp_port: 587
authelia_smtp_from: no-reply@{{ authelia_domain }}
authelia_smtp_subject: "[2FA] {title}"
authelia_smtp_disable_require_tls: false

authelia_jwt_token:
authelia_session_token:
authelia_smtp_username:
authelia_smtp_password:
authelia_admin_username:
authelia_admin_password:
authelia_admin_email:
authelia_admin_display_name:
authelia_encryption_key:
