---
- name: Install management services
  hosts: all
  vars_files:
    - ../../vars/common.yml
    - ../../vars/secrets.yml
  become: true
  gather_facts: false

  roles:
    # https://hub.docker.com/r/portainer/portainer/tags
    - role: portainer
      portainer_image_tag: 1.24.2-alpine
      portainer_fqdn: docker.{{ vault_domain }}
      portainer_install_path: "{{ common_install_root }}/portainer"
