---
version: '3.8'

services:
  # logging handled in traefik and authelia
  # does not run as root
  hydra:
    image: linuxserver/nzbhydra2:${VERSION}
    container_name: hydra
    restart: unless-stopped
    init: true
    networks:
      traefik:
        aliases:
          - ${DOMAIN}
    expose:
      - 5076
    environment:
      TZ: ${TIMEZONE}
      PUID: ${PUID}
      PGID: ${PGID}
    volumes:
      - ${DATA_PATH}:/config
      # - ${NZB_DOWNLOAD_PATH}:/downloads
    labels:
      traefik.enable: true
      traefik.http.routers.hydra.service: hydra
      traefik.http.routers.hydra.rule: Host(`${DOMAIN}`)
      traefik.http.routers.hydra.entrypoints: https
      traefik.http.routers.hydra.tls: true
      traefik.http.services.hydra.loadbalancer.server.port: 5076
      traefik.http.routers.hydra.middlewares: internal-secured


networks:
  traefik:
    name: traefik
    external: true
