---
targets:
  - src: install
    dest: "{{ common_install_root }}/authelia"
  - src: data
    dest: "{{ common_data_root }}/authelia"
  - dest: "{{ common_logs_root }}/authelia"

users:
  - user: authelia

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*

  - owner: authelia
    group: authelia
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install/secrets
      - install/secrets/*

  - owner: authelia
    group: authelia
    mode: '0440'
    dir_mode: '0750'
    paths:
      - "{{ common_logs_root }}/authelia"
      - data
      - data/*
