---
- name: Ensure filebeat directories
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0550
    state: directory
  loop:
    - "{{ filebeat_install_path }}"
    - "{{ filebeat_install_path }}/config"
