---
- name: Ensure user group exist.
  ansible.builtin.group:
    name: "{{ sabnzb_group }}"
    state: present

- name: Ensure service users exist.
  ansible.builtin.user:
    name: "{{ sabnzb_user }}"
    group: "{{ sabnzb_group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present

- name: Export group IDs
  ansible.builtin.getent:
    database: group
    key: "{{ sabnzb_group }}"
  changed_when: false
  register: getent_groups

- name: Export user IDs
  ansible.builtin.getent:
    database: passwd
    key: "{{ sabnzb_user }}"
  changed_when: false
  register: getent_users

- name: Gather user facts
  ansible.builtin.set_fact:
    sabnzb_user_id: "{{ getent_passwd[sabnzb_user][1] }}"
    sabnzb_group_id: "{{ getent_group[sabnzb_group][1] }}"
