---
- import_tasks: users.yml

- import_tasks: directories.yml

- name: Install deluge files
  copy:
    src: docker-compose.yml
    dest: "{{ deluge_install_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0440
  notify:
    - restart deluge

- name: Install deluge wait-for-vpn fix
  copy:
    src: wait/90-wait-for-vpn.sh
    dest: "{{ deluge_install_path }}/wait/90-wait-for-vpn.sh"
    owner: root
    group: root
    mode: 0755
  notify:
    - restart deluge

- name: Copying environment file
  template:
    src: ".env.j2"
    dest: "{{ deluge_install_path }}/.env"
    owner: root
    group: root
    mode: 0440
  notify:
    - restart deluge

- name: Check if running
  command:
    cmd: docker ps -qf name="deluge"
  register: this
  changed_when: not this.stdout
  failed_when: false
  notify: restart deluge
