---
- name: Ensure {{ role_name }} docker directory
  file:
    path: "{{ item }}"
    owner: root
    group: root
    mode: 0550
    state: directory
  loop:
    - "{{ plex_install_path }}"
    - "{{ plex_install_path }}/bin"

- name: Ensure {{ role_name }} cache directory
  file:
    path: "{{ plex_cache_path }}"
    owner: "{{ plex_user }}"
    group: "{{ plex_group }}"
    mode: 0750
    state: directory

- name: Ensure transcode directory
  file:
    path: "{{ plex_transcode_path }}"
    owner: "{{ plex_user }}"
    group: "{{ plex_group }}"
    mode: 0750
    state: directory
  when: plex_transcode_path != '/dev/shm'
