---
- name: Ensure installation directory exists.
  ansible.builtin.file:
    path: "{{ bitwarden_install_path }}"
    state: directory
    owner: root
    group: root
    mode: "0550"
    recurse: false

- name: Ensure configuration directory exists.
  ansible.builtin.file:
    path: "{{ bitwarden_config_path }}"
    state: directory
    owner: root
    group: root
    mode: "0750"
    recurse: false

- name: Ensure logs directory exists.
  ansible.builtin.file:
    path: "{{ bitwarden_logs_path }}"
    state: directory
    owner: root
    group: root
    mode: "0750"
    recurse: false
