---
- name: "restart {{ container }}"
  command:
    chdir: "{{ _containers_compose_root[container] }}"
    cmd: docker compose up -d --quiet-pull --force-recreate
  when: container in _containers_compose_root and manifest.stack.skip_handler | default(False) | bool == False