---
- name: "restart {{ container }}"
  command:
    chdir: "{{ manifest.stack.compose_directory }}"
    cmd: docker compose up -d --quiet-pull --force-recreate
  when: manifest.stack.skip_handler | default(False) | bool == False