---
targets:
  - src: install
    dest: "{{ common_install_root }}/sabnzb"
  - dest: "{{ common_data_root }}/sabnzb"
  - dest: "{{ common_downloads_root }}/nzb"
  - dest: "{{ common_downloads_root }}/nzb-incomplete"

users:
  - user: "{{ common_downloads_user }}"
    group: "{{ common_downloads_group }}"

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*

  - owner: "{{ common_downloads_user }}"
    group: "{{ common_downloads_group }}"
    dir_mode: '0750'
    paths:
      - "{{ common_data_root }}/sabnzb"

  - owner: "{{ common_downloads_user }}"
    group: "{{ common_downloads_group }}"
    dir_mode: '0770'
    paths:
      - "{{ common_downloads_root }}/nzb-incomplete"
      - "{{ common_downloads_root }}/nzb"
