---
- name: Ensure required directories exist
  file:
    path: "{{ item }}"
    state: directory
    owner: root
    group: root
    mode: 0750
  loop:
    - "{{ restic_install_path }}"
    - "{{ restic_config_path }}"
  loop_control:
    label: "{{ item }}"

- name: Get current version
  shell:
    cmd: restic version
  register: restic_current_version
  changed_when: false
  failed_when: false

- name: Install restic
  import_tasks: install.yml
  when: "'restic ' + restic_version not in restic_current_version.stdout"

- name: Ensure repo exists
  stat:
    path: "{{ restic_schedule_repos_root }}/{{ restic_repo }}/config"
  register: repo_config
  changed_when: false

- name: Create repo
  shell:
    cmd: "restic init -r {{ restic_schedule_repos_root }}/{{ restic_repo }} --password-command 'echo \"{{ restic_repo_password }}\"'"
  when: not repo_config.stat.exists
