############
# PACKAGES #
############

docker_buildx_version: 0.23.0
docker_compose_version: 2.35.1
docker_version: 28.1.1
docker_containerd_version: 1.7.27


##############
# CONTAINERS #
##############

# https://github.com/authelia/authelia/releases
authelia_tag: 4.39.6
authelia_force_pull: false
authelia_ensure_running: true
authelia_fqdn: auth.{{ vault_domain }}
authelia_jwt_token: "{{ vault_jwt_token }}"
authelia_session_token: "{{ vault_session_token }}"

# https://hub.docker.com/r/vaultwarden/server/tags
bitwarden_tag: 1.34.3-alpine
bitwarden_force_pull: false
bitwarden_ensure_running: true
bitwarden_fqdn: warden.{{ vault_domain }}
bitwarden_smtp_from: "{{ common_smtp_from }}"

# https://github.com/linuxserver/docker-ddclient/releases
ddclient_tag: v4.0.0-ls206
ddclient_force_pull: false
ddclient_ensure_running: true

# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html
elasticsearch_tag: 9.1.2
elasticsearch_force_pull: false
elasticsearch_ensure_running: true
elasticsearch_fqdn: kibana.{{ vault_domain }}
elasticsearch_username: "{{ vault_elastic_username }}"
elasticsearch_password: "{{ vault_elastic_password }}"

# https://hub.docker.com/r/crazymax/fail2ban/tags
fail2ban_tag: 1.1.0
fail2ban_force_pull: false
fail2ban_ensure_running: true
fail2ban_domain: "{{ vault_domain }}"
fail2ban_admin_email: "{{ vault_smtp_username }}"
fail2ban_email_from: "{{ common_smtp_from }}"

