---
stack:
  name: tautulli
  ensure_running:
    - tautulli
  compose_directory: "{{ common_install_root }}/tautulli"

targets:
  - src: install
    dest: "{{ common_install_root }}/tautulli"
  - dest: "{{ common_data_root }}/tautulli"

users:
  - user: tautulli

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*

  - owner: tautulli
    group: tautulli
    dir_mode: '0750'
    paths:
      - "{{ common_data_root }}/tautulli"
