---
stack:
  name: organizr
  ensure_running:
    - organizr
  compose_directory: "{{ common_install_root }}/organizr"
  force_pull: true

targets:
  - src: install
    dest: "{{ common_install_root }}/organizr"
  - dest: "{{ common_data_root }}/organizr"

users:
  - user: organizr

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*

  - owner: organizr
    group: organizr
    mode: '0440'
    dir_mode: '0750'
    paths:
      - "{{ common_data_root }}/organizr"
