---
version: '3.8'

services:
  calibre:
    image: gotson/komga:${VERSION}
    container_name: komga
    restart: unless-stopped
    init: true
    user: "${PUID}:${PGID}"
    # environment:
    #  JAVA_TOOL_OPTIONS: -Xmx4g
    networks:
      - traefik
    expose:
      - 8080
    volumes:
      - ${DATA_PATH}:/config
      - ${MEDIA_PATH}:/data:ro
      - /etc/timezone:/etc/timezone:ro
    labels:
      traefik.enable: true
      traefik.http.routers.komga.service: komga
      traefik.http.routers.komga.rule: Host(`${DOMAIN}`)
      traefik.http.routers.komga.entrypoints: https
      traefik.http.routers.komga.tls: true
      traefik.http.services.komga.loadbalancer.server.port: 8080


networks:
  traefik:
    name: traefik
    external: true
