---
- name: Add Debian/Ubuntu Docker Repo
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/\
      {{ ansible_distribution|lower }} {{ ansible_distribution_release }} \
      stable"
    filename: docker
    state: present

- name: Remove old docker packages
  package:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent

- name: Install docker
  package:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
  notify:
    - restart docker

- import_tasks: compose.yml
