---
version: '3.8'

services:
  elasticsearch:
    restart: unless-stopped
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${VERSION}
    environment:
      discovery.type: single-node
      xpack.security.enabled: 'true'
      ELASTIC_PASSWORD: ${ES_PASSWORD}
      ES_JAVA_OPTS: -Xms4G -Xmx4G
    networks:
      - elastic
    ports:
      - 9200:9200
      - 9300:9300
    expose:
      - 9200
      - 9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - es_data:/usr/share/elasticsearch/data

# /usr/share/elasticsearch/modules/ingest-geoip/GeoLite2-Country.mmdb
# /usr/share/elasticsearch/modules/ingest-geoip/GeoLite2-ASN.mmdb
# /usr/share/elasticsearch/modules/ingest-geoip/geoip2-2.13.1.jar
# /usr/share/elasticsearch/modules/ingest-geoip/GeoLite2-City.mmdb


  kibana:
    depends_on:
      - elasticsearch
    restart: unless-stopped
    container_name: kibana
    image: docker.elastic.co/kibana/kibana:${VERSION}
    networks:
      - traefik
      - elastic
    environment:
      ELASTICSEARCH_USERNAME: ${ES_USERNAME}
      ELASTICSEARCH_PASSWORD: ${ES_PASSWORD}
    expose:
      - 5601
    volumes:
      - ./config/kibana.yml:/usr/share/kibana/config/kibana.yml:ro
    labels:
      traefik.enable: true
      traefik.docker.network: traefik
      traefik.http.routers.kibana.service: kibana
      traefik.http.routers.kibana.rule: Host(`${DOMAIN}`)
      traefik.http.routers.kibana.entrypoints: https
      traefik.http.routers.kibana.tls: true
      traefik.http.services.kibana.loadbalancer.server.port: 5601
      traefik.http.routers.kibana.middlewares: internal-only

volumes:
  es_data:
    name: elasticsearch_es_data
    external: true

networks:
  traefik:
    name: traefik
    external: true
  elastic:
    name: elastic
    external: true
