---
- name: Add ddclient group {{ ddclient_group }}
  group:
    name: "{{ ddclient_group }}"
    state: present

- name: Add ddclient user {{ ddclient_user }}
  user:
    name: "{{ ddclient_user }}"
    group: "{{ ddclient_group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present

- name: Export {{ ddclient_group }} group id
  getent:
    database: group
    key: "{{ ddclient_group }}"

- name: Export {{ ddclient_user }} user id
  getent:
    database: passwd
    key: "{{ ddclient_user }}"

- name: Gather created username and group IDs
  set_fact:
    ddclient_user_id: "{{ getent_passwd[ddclient_user][1] }}"
    ddclient_group_id: "{{ getent_group[ddclient_group][1] }}"
