---
- name: Restart Deluge
  ansible.builtin.command:
    chdir: "{{ deluge_install_path }}"
    cmd: "{{ item.command }}"
  changed_when: true
  when: not deluge_skip_handler
  loop_control:
    label: "{{ item.name }}"
  loop:
    - name: Build if needed
      command: docker compose build --no-cache
    - name: Pulling image
      command: docker compose pull --ignore-buildable
    - name: Restarting container
      command: docker compose up -d --force-recreate
