---
- name: Ensure fail2ban docker directory
  file:
    path: "{{ fail2ban_install_path }}"
    owner: root
    group: root
    mode: 0550
    state: directory

- name: Ensure fail2ban config directory
  file:
    path: "{{ fail2ban_install_path }}/config/{{ item }}"
    owner: root
    group: root
    mode: 0550
    state: directory
  loop:
    - action.d
    - filter.d
    - jail.d

- name: Ensure fail2ban data directory
  file:
    path: "{{ fail2ban_data_path }}"
    owner: root
    group: root
    mode: 0750
    state: directory

- name: Ensure fail2ban log directory
  file:
    path: "{{ fail2ban_log_path }}"
    owner: root
    group: root
    mode: 0750
    state: directory
