---
- name: Add nvidia repository GPG key [Debian/Ubuntu]
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: Add nvidia repository
  get_url:
    url: "{{ _nvidia_repo_url }}"
    dest: /etc/apt/sources.list.d/nvidia-docker.list
  register: nvidia_repo

- name: Update apt  # noqa 503
  apt:
    update_cache: true
  when: nvidia_repo.changed

- name: Install nvidia container packages
  package:
    name:
      - nvidia-docker2={{ nvidia_docker2_version }}-1
      # - nvidia-container-toolkit={{ nvidia_container_version }}
    state: present
  notify:
    - restart docker
