---
- name: Add nvidia repository GPG key [Debian/Ubuntu]
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: Add nvidia repository
  ansible.builtin.get_url:
    url: "{{ _nvidia_repo_url }}"
    dest: /etc/apt/sources.list.d/nvidia-docker.list
    mode: "0440"

- name: Update apt
  ansible.builtin.apt:
    update_cache: true
    name: nvidia-docker2={{ nvidia_docker2_version }}-1
    state: present
  notify:
    - Restart docker
