---
- name: Unload nouveau
  modprobe:
    name: nouveau
    state: absent

- name: Ensure latest nvidia driver
  package:
    name: nvidia-headless-{{ nvidia_driver_version }}
    state: present

- name: Add nvidia repository GPG key [Debian/Ubuntu]
  apt_key:
    url: https://nvidia.github.io/nvidia-docker/gpgkey
    state: present

- name: Add nvidia repository
  get_url:
    url: "https://nvidia.github.io/nvidia-docker/\
      {{ ansible_distribution | lower }}\
      {{ ansible_distribution_version }}/nvidia-docker.list"
    dest: /etc/apt/sources.list.d/nvidia-docker.list
  register: nvidia_repo

- name: Update apt  # noqa 503
  apt:
    update_cache: true
  when: nvidia_repo.changed

- name: Install nvidia container packages
  package:
    name:
      - nvidia-docker2={{ nvidia_docker2_version }}
      - nvidia-container-toolkit={{ nvidia_container_version }}
    state: present
  notify:
    - restart docker
