---
- name: Unload nouveau
  community.general.modprobe:
    name: nouveau
    state: absent

- name: Ensure latest nvidia driver
  ansible.builtin.package:
    name: nvidia-headless-{{ nvidia_driver_version }}
    state: present

- name: NVIDIA Docker Runtime
  ansible.builtin.import_tasks: docker.yml
  when: nvidia_install_docker_runtime
