---
- name: Unload nouveau
  modprobe:
    name: nouveau
    state: absent

- name: Ensure latest nvidia driver
  package:
    name: nvidia-headless-{{ nvidia_driver_version }}
    state: present

- import_tasks: docker.yml
  when: nvidia_install_docker_runtime == true
