---
- name: Check for existing networks
  command: docker network ls -q -f name={{ item }}
  register: existing_networks
  loop: "{{ network_names }}"
  changed_when: false
  failed_when: false

- name: Create docker networks
  command: docker network create {{ item.item }}
  loop: "{{ existing_networks.results }}"
  loop_control:
    label: "{{ item.item }}"
  when: not item.stdout
