---
ansible_ssh_user: "{{ vault_ansible_ssh_user }}"
ansible_become_pass: "{{ vault_ansible_become_pass }}"
proxy_internal_only_networks:
  - 172.16.0.0/12
  - 192.168.1.0/24
  - 192.168.111.0/24
advertise_ip: 192.168.111.128
docker_runtime: runc
traefik_override: true
