---
version: '3.8'

services:
  # logging handled in traefik and authelia
  # does not run as root
  nzbget:
    image: linuxserver/nzbget:${VERSION}
    container_name: nzbget
    restart: unless-stopped
    init: true
    networks:
      traefik:
        aliases:
          - ${DOMAIN}
    expose:
      - 6789
    environment:
      PUID: ${PUID}
      PGID: ${PGID}
      TZ: ${TIMEZONE}
    volumes:
      - ${DATA_PATH}:/config
      - ${DOWNLOADS_PATH}:/downloads
      - ${SOFTWARE_ROOT}:/data
    labels:
      traefik.enable: true
      traefik.http.routers.nzbget.service: nzbget
      traefik.http.routers.nzbget.rule: Host(`${DOMAIN}`)
      traefik.http.routers.nzbget.entrypoints: https
      traefik.http.routers.nzbget.tls: true
      traefik.http.services.nzbget.loadbalancer.server.port: 6789
      traefik.http.routers.nzbget.middlewares: authelia


networks:
  traefik:
    name: traefik
    external: true
