---
- name: Ensure user group exist.
  ansible.builtin.group:
    name: "{{ radarr_group }}"
    state: present

- name: Ensure service users exist.
  ansible.builtin.user:
    name: "{{ radarr_user }}"
    group: "{{ radarr_group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present

- name: Export group IDs
  ansible.builtin.getent:
    database: group
    key: "{{ radarr_group }}"
  changed_when: false
  register: getent_groups

- name: Export user IDs
  ansible.builtin.getent:
    database: passwd
    key: "{{ radarr_user }}"
  changed_when: false
  register: getent_users

- name: Gather user facts
  ansible.builtin.set_fact:
    radarr_user_id: "{{ getent_passwd[radarr_user][1] }}"
    radarr_group_id: "{{ getent_group[radarr_group][1] }}"
