---
- name: Configure common items
  hosts: all
  vars_files:
    - ../../vars/common.yml
    - ../../vars/secrets.yml
  become: true
  gather_facts: false

  tasks:
    - name: Ensure common data directory exists
      file:
        path: "{{ common_data_root }}"
        owner: root
        group: root
        mode: 0440
        state: directory

    - name: Ensure common download directory exists
      file:
        path: "{{ common_downloads_root }}"
        owner: "{{ common_downloads_user }}"
        group: "{{ common_downloads_group }}"
        mode: 0550
        state: directory

    - name: Ensure common install directory
      file:
        path: "{{ common_install_path }}"
        owner: root
        group: root
        mode: 0550
        state: directory

    - name: Ensure common log directory exists
      file:
        path: "{{ common_logs_root }}"
        owner: root
        group: root
        mode: 0440
        state: directory

    - name: Update apt cache if needed
      apt:
        update_cache: true
        cache_valid_time: 86400

    - name: Install ACL package
      package:
        name: acl
        state: present
