---
- name: Install Downloaders
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../vars/secrets
    - ../config/versions.yml
    - ../config/vpn.yml
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  post_tasks:
    - name: Cleanup old images
      ansible.builtin.command:
        cmd: "docker image prune -a --force"
      register: this
      changed_when: "'Deleted Images' in this.stdout"

  roles:
    - role: docker
      docker_networks:
        - "{{ common_traefik_network_name }}"
      docker_volumes:
        - "{{ common_docker_software_mount }}"

    - role: containers/sabnzb
      sabnzb_user: "{{ common_downloads_user }}"
      sabnzb_group: "{{ common_downloads_group }}"
      sabnzb_config_path: "{{ common_data_root }}/sabnzb"
      sabnzb_install_path: "{{ common_install_root }}/sabnzb"
      sabnzb_downloads_root: "{{ common_downloads_root }}"

    - role: containers/deluge
      deluge_user: "{{ common_downloads_user }}"
      deluge_group: "{{ common_downloads_group }}"
      deluge_config_path: "{{ common_data_root }}/deluge"
      deluge_install_path: "{{ common_install_root }}/deluge"
      deluge_downloads_path: "{{ common_downloads_root }}/torrent"
