---
- name: Install Indexers
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../vars/secrets
    - ../config/versions.yml
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  post_tasks:
    - name: Cleanup old images
      ansible.builtin.command:
        cmd: "docker image prune -a --force"
      register: this
      changed_when: "'Deleted Images' in this.stdout"

  roles:
    - role: docker
      docker_networks:
        - "{{ common_traefik_network_name }}"

    - role: containers/prowlarr
      prowlarr_config_path: "{{ common_data_root }}/prowlarr"
      prowlarr_install_path: "{{ common_install_root }}/prowlarr"
