---
- name: Install Indexers
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../vars/secrets
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      apt:
        update_cache: true
        cache_valid_time: 86400

  roles:
    - role: common
      common_script_name: "{{ vault_stack_name | lower }}"

    - role: docker
      docker_version: "{{ common_docker_version }}"
      docker_containerd_version: "{{ common_docker_containerd_version }}"
      docker_compose_version: "{{ common_docker_compose_version }}"
      docker_networks:
        - "{{ common_traefik_network_name }}"

    # https://github.com/linuxserver/docker-nzbhydra2/releases
    - role: hydra
      hydra_image_tag: v3.17.3-ls35
      hydra_fqdn: hydra.{{ vault_domain }}
      hydra_data_path: "{{ common_data_root }}/hydra"
      hydra_install_path: "{{ common_install_root }}/hydra"

    # https://github.com/linuxserver/docker-jackett/releases
    - role: jackett
      jackett_image_tag: v0.19.162-ls50
      jackett_fqdn: jackett.{{ vault_domain }}
      jackett_data_path: "{{ common_data_root }}/jackett"
      jackett_install_path: "{{ common_install_root }}/jackett"
