---
- name: Install and configure required infra
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../vars/secrets
    - ../config/versions.yml
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  post_tasks:
    - name: Cleanup old images
      ansible.builtin.command:
        cmd: "docker image prune -a --force"
      register: this
      changed_when: "'Deleted Images' in this.stdout"

  roles:
    - role: docker
      docker_networks:
        - "{{ common_traefik_network_name }}"
        - "{{ common_pusher_network_name }}"

    - role: containers/ddclient
      ddclient_config_path: "{{ common_install_root }}/ddclient/config"
      ddclient_install_path: "{{ common_install_root }}/ddclient"
      ddclient_config_file: "{{ playbook_dir ~ '/../config/ddclient/ddclient.conf' }}"

    - role: containers/traefik
      traefik_config_path: "{{ common_data_root }}/traefik"
      traefik_install_path: "{{ common_install_root }}/traefik"
      traefik_logs_path: "{{ common_logs_root }}/traefik"
      traefik_allowed_networks: "{{ proxy_internal_only_networks }}"

    - role: containers/pihole
      pihole_config_path: "{{ common_data_root }}/pihole"
      pihole_install_path: "{{ common_install_root }}/pihole"
      pihole_advertise_ip: "{{ advertise_ip }}"
