---
- name: Install and configure required infra
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../configs/versions.yml
    - ../vars/secrets
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  post_tasks:
    - name: Cleanup old images
      ansible.builtin.command:
        cmd: "docker image prune -a --force"
      register: this
      changed_when: "'Deleted Images' in this.stdout"

  roles:
#    - role: docker
#      docker_networks:
#        - "{{ common_traefik_network_name }}"
#        - "{{ common_pusher_network_name }}"
#
    - role: containers/ddclient
      ddclient_config_path: "{{ common_install_root }}/ddclient/config"
      ddclient_install_path: "{{ common_install_root }}/ddclient"
      ddclient_config_file: "{{ playbook_dir ~ '/../configs/ddclient/ddclient.conf' }}"
#
#    - role: container
#      container_name: traefik
#
#    - role: container
#      container_name: pihole
