---
- name: Install and configure required infra
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../containers/versions.yml
    - ../vars/secrets
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  post_tasks:
    - name: Cleanup old images
      ansible.builtin.command:
        cmd: "docker image prune -a --force"
      register: this
      changed_when: "'Deleted Images' in this.stdout"

  roles:
    - role: docker
      docker_networks:
        - "{{ common_traefik_network_name }}"
        - "{{ common_pusher_network_name }}"

    - role: container
      container_name: common

    - role: container
      container_name: ddclient

    - role: container
      container_name: traefik

    - role: container
      container_name: pihole
