---
- name: Install and configure logging
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../containers/versions.yml
    - ../vars/secrets
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  post_tasks:
    - name: Cleanup old images
      ansible.builtin.command:
        cmd: "docker image prune -a --force"
      register: this
      changed_when: "'Deleted Images' in this.stdout"

  roles:
    - role: docker
      docker_volumes:
        - name: filebeat_registry
        - name: elasticsearch_es_data
      docker_networks:
        - "{{ common_traefik_network_name }}"
        - elastic

    - role: container
      container: common

    - role: container
      container: elasticsearch

    - role: container
      container: filebeat
