---
- name: Install and configure logging
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../configs/versions.yml
    - ../vars/secrets
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  post_tasks:
    - name: Cleanup old images
      ansible.builtin.command:
        cmd: "docker image prune -a --force"
      register: this
      changed_when: "'Deleted Images' in this.stdout"

  roles:
    - role: containers/elasticsearch
      elasticsearch_install_path: "{{ common_install_root }}/elasticsearch"
      elasticsearch_config_path: "{{ common_install_root }}/elasticsearch/config"

#    - role: docker
#      docker_volumes:
#        - name: filebeat_registry
#        - name: elasticsearch_es_data
#      docker_networks:
#        - "{{ common_traefik_network_name }}"
#        - elastic
#
#    - role: container
#      container_name: common
#
#    - role: container
#      container_name: elasticsearch
#
#    - role: container
#      container_name: filebeat
