---
- name: Install and configure logrotate
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../vars/secrets
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  roles:
    - role: logrotate
      logrotate_scripts:
        - name: traefik
          paths:
            - "{{ common_logs_root }}/traefik/*.log"
          options:
            - daily
            - rotate 30
            - missingok
            - notifempty
            - dateext
            - dateformat .%Y-%m-%d
            - create 0640 traefik traefik
          scripts:
            postrotate: docker kill --signal=USR1 traefik

        - name: authelia
          paths:
            - "{{ common_logs_root }}/authelia/authelia.log"
          options:
            - daily
            - rotate 0
            - copytruncate
            - dateext
            - dateformat .%Y-%m-%d
            - missingok
            - notifempty

        - name: bitwarden
          paths:
            - "{{ common_logs_root }}/bitwarden/bitwarden.log"
          options:
            - daily
            - rotate 0
            - copytruncate
            - dateext
            - dateformat .%Y-%m-%d
            - missingok
            - notifempty

        - name: fail2ban
          paths:
            - "{{ common_logs_root }}/fail2ban/fail2ban.log"
          options:
            - daily
            - rotate 30
            - create 0640 root root
            - dateext
            - dateformat .%Y-%m-%d
            - missingok
            - notifempty
          scripts:
            postrotate: docker exec -it fail2ban-client flushlogs 1>/dev/null || true
