---
- name: Install media management services
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../containers/versions.yml
    - ../vars/secrets
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  post_tasks:
    - name: Cleanup old images
      ansible.builtin.command:
        cmd: "docker image prune -a --force"
      register: this
      changed_when: "'Deleted Images' in this.stdout"

  roles:
    - role: docker
      docker_networks:
        - "{{ common_traefik_network_name }}"
      docker_volumes:
        - "{{ common_docker_media_mount }}"

    - role: container
      container_name: common

    - role: container
      container_name: sonarr

    - role: container
      container_name: radarr

    - role: container
      container_name: lidarr

    - role: container
      container_name: whisparr

    - role: container
      container_name: readarr
