---
- name: Install media management services
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../vars/secrets
    - ../config/versions.yml
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  post_tasks:
    - name: Cleanup old images
      ansible.builtin.command:
        cmd: "docker image prune -a --force"
      register: this
      changed_when: "'Deleted Images' in this.stdout"

  roles:
    - role: docker
      docker_networks:
        - "{{ common_traefik_network_name }}"
      docker_volumes:
        - "{{ common_docker_media_mount }}"

    - role: containers/sonarr
      sonarr_user: "{{ common_downloads_user }}"
      sonarr_group: "{{ common_downloads_group }}"
      sonarr_config_path: "{{ common_data_root }}/sonarr"
      sonarr_install_path: "{{ common_install_root }}/sonarr"
      sonarr_downloads_path: "{{ common_downloads_root }}"

    - role: containers/radarr
      radarr_user: "{{ common_downloads_user }}"
      radarr_group: "{{ common_downloads_group }}"
      radarr_config_path: "{{ common_data_root }}/radarr"
      radarr_install_path: "{{ common_install_root }}/radarr"
      radarr_downloads_path: "{{ common_downloads_root }}"

    - role: containers/lidarr
      lidarr_user: "{{ common_downloads_user }}"
      lidarr_group: "{{ common_downloads_group }}"
      lidarr_config_path: "{{ common_data_root }}/lidarr"
      lidarr_install_path: "{{ common_install_root }}/lidarr"
      lidarr_downloads_path: "{{ common_downloads_root }}"

    - role: containers/whisparr
      whisparr_user: "{{ common_downloads_user }}"
      whisparr_group: "{{ common_downloads_group }}"
      whisparr_config_path: "{{ common_data_root }}/whisparr"
      whisparr_install_path: "{{ common_install_root }}/whisparr"
      whisparr_downloads_path: "{{ common_downloads_root }}"

    - role: containers/readarr
      readarr_user: "{{ common_downloads_user }}"
      readarr_group: "{{ common_downloads_group }}"
      readarr_config_path: "{{ common_data_root }}/readarr"
      readarr_install_path: "{{ common_install_root }}/readarr"
      readarr_downloads_path: "{{ common_downloads_root }}"
