---
- name: Install plex related services
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../vars/secrets
    - ../config/versions.yml
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  post_tasks:
    - name: Cleanup old images
      ansible.builtin.command:
        cmd: "docker image prune -a --force"
      register: this
      changed_when: "'Deleted Images' in this.stdout"

  roles:
    - role: docker
      docker_networks:
        - "{{ common_traefik_network_name }}"
      docker_volumes:
        - "{{ common_docker_media_mount }}"

    # this isn't working currently, installing nvidia drivers on linux
    # is a pain in the ass
    # - role: nvidia
    #   nvidia_driver_version: 495
    #   nvidia_docker2_version: 2.6.0-1
    #   nvidia_container_version: 1.5.1-1

    - role: containers/static
      static_www_root: "{{ common_data_root }}/static"
      static_install_path: "{{ common_install_root }}/static"

    - role: containers/plex
      plex_install_path: "{{ common_install_root }}/plex"
      plex_advertise_ip: "{{ advertise_ip }}"

    - role: containers/organizr
      organizr_config_path: "{{ common_data_root }}/organizr"
      organizr_install_path: "{{ common_install_root }}/organizr"

    - role: containers/overseerr
      overseerr_config_path: "{{ common_data_root }}/overseerr"
      overseerr_install_path: "{{ common_install_root }}/overseerr"

#      deprecated
#    - role: container
#      container_name: ombi

    - role: containers/tautulli
      tautulli_config_path: "{{ common_data_root }}/tautulli"
      tautulli_install_path: "{{ common_install_root }}/tautulli"
      plex_logs_path: "/cache/plex/Library/Application Support/Plex Media Server/Logs"