---
- name: Install plex related services
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../vars/secrets
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      apt:
        update_cache: true
        cache_valid_time: 86400

  roles:
    - role: common
      common_script_name: "{{ vault_stack_name | lower }}"

    - role: docker
      docker_version: "{{ common_docker_version }}"
      docker_containerd_version: "{{ common_docker_containerd_version }}"
      docker_compose_version: "{{ common_docker_compose_version }}"
      docker_networks:
        - "{{ common_traefik_network_name }}"

    - role: nvidia
      nvidia_driver_version: 495
      nvidia_docker2_version: 2.6.0-1
      nvidia_container_version: 1.5.1-1

    - role: static
      static_fqdn: static.{{ vault_domain }}
      static_data_path: "{{ common_data_root }}/static"
      static_install_path: "{{ common_install_root }}/static"

    - role: plex
      plex_image_tag: plexpass
      plex_cache_path: /cache/plex
      plex_runtime: "{{ docker_runtime }}"
      plex_fqdn: watch.{{ vault_domain }}
      plex_advertise_ip: "{{ advertise_ip }}"
      plex_media_root: /mnt/media
      plex_username: "{{ vault_plex_username }}"
      plex_password: "{{ vault_plex_password }}"
      plex_install_path: "{{ common_install_root }}/plex"

    # latest only
    - role: organizr
      organizr_domain: "{{ vault_domain }}"
      organizr_data_path: "{{ common_data_root }}/organizr"
      organizr_install_path: "{{ common_install_root }}/organizr"

    # https://github.com/linuxserver/docker-ombi/releases
    - role: ombi
      ombi_image_tag: v4.3.3-ls110
      ombi_fqdn: request.{{ vault_domain }}
      ombi_data_path: "{{ common_data_root }}/ombi"
      ombi_install_path: "{{ common_install_root }}/ombi"

    # https://github.com/linuxserver/docker-tautulli/releases
    - role: tautulli
      tautulli_image_tag: v2.7.7-ls23
      tautulli_fqdn: stats.{{ vault_domain }}
      tautulli_data_path: "{{ common_data_root }}/tautulli"
      tautulli_plex_logs_path: >-
        /cache/plex/Library/Application Support/Plex Media Server/Logs
      tautulli_install_path: "{{ common_install_root }}/tautulli"
