---
- name: Install plex related services
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../containers/versions.yml
    - ../vars/secrets
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  post_tasks:
    - name: Cleanup old images
      ansible.builtin.command:
        cmd: "docker image prune -a --force"
      register: this
      changed_when: "'Deleted Images' in this.stdout"

  roles:
    - role: docker
      docker_networks:
        - "{{ common_traefik_network_name }}"
      docker_volumes:
        - "{{ common_docker_media_mount }}"

    - role: container
      container: common

    # this isn't working currently, installing nvidia drivers on linux
    # is a pain in the ass
    # - role: nvidia
    #   nvidia_driver_version: 495
    #   nvidia_docker2_version: 2.6.0-1
    #   nvidia_container_version: 1.5.1-1

    - role: container
      container: static

    - role: container
      container: plex

    - role: container
      container: organizr

    - role: container
      container: overseerr

#    - role: container
#      container: ombi

    - role: container
      container: tautulli

