---
- name: Install security based services
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../configs/versions.yml
    - ../vars/secrets
    - ../configs/authelia/users.yml
  become: true
  gather_facts: true

#  pre_tasks:
#    - name: Update apt cache if needed
#      ansible.builtin.apt:
#        update_cache: true
#        cache_valid_time: 86400
#
#  post_tasks:
#    - name: Cleanup old images
#      ansible.builtin.command:
#        cmd: "docker image prune -a --force"
#      register: this
#      changed_when: "'Deleted Images' in this.stdout"

  roles:
#    - role: docker
#      docker_networks:
#        - "{{ common_traefik_network_name }}"
#
#    - role: container
#      container_name: postfix
#
    - role: containers/authelia
      authelia_install_path: "{{ common_install_root }}/authelia"
      authelia_logs_path: "{{ common_logs_root }}/authelia"
      authelia_config_path: "{{ common_data_root }}/authelia"
      authelia_config_file: "{{ playbook_dir ~ '/../configs/authelia/config.yml' }}"

    - role: containers/fail2ban
      fail2ban_config_path: "{{ common_data_root }}/fail2ban"
      fail2ban_install_path: "{{ common_install_root }}/fail2ban"
      fail2ban_logs_path: "{{ common_logs_root }}/fail2ban"
      fail2ban_ingest_path: "{{ common_data_root }}/logs"
