---
- name: Install security based services
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../vars/secrets
  become: true
  gather_facts: false

  pre_tasks:
    - name: Update apt cache if needed
      apt:
        update_cache: true
        cache_valid_time: 86400

  roles:
    - role: common
      common_script_name: "{{ vault_stack_name | lower }}"

    - role: docker
      docker_version: "{{ common_docker_version }}"
      docker_containerd_version: "{{ common_docker_containerd_version }}"
      docker_compose_version: "{{ common_docker_compose_version }}"
      docker_networks:
        - "{{ common_traefik_network_name }}"

    - role: postfix
      postfix_smtp_server: smtp-relay.gmail.com
      postfix_smtp_port: 587
      postfix_smtp_username: "{{ vault_smtp_username }}"
      postfix_smtp_password: "{{ vault_smtp_password }}"
      postfix_domain: "{{ vault_domain }}"
      postfix_install_path: "{{ common_install_root }}/postfix"

    # https://github.com/authelia/authelia/releases
    - role: authelia
      authelia_image_tag: 4.33.1
      authelia_domain: "{{ vault_domain }}"
      authelia_log_path: "{{ common_logs_root }}/authelia"
      authelia_data_path: "{{ common_data_root }}/authelia"
      authelia_totp_issuer: "{{ vault_stack_name }}"
      authelia_default_redirection_url: "{{ vault_domain }}"
      authelia_session_cookie: "{{ vault_stack_name }}_session"
      authelia_smtp_server: postfix
      authelia_smtp_port: 25
      authelia_smtp_disable_require_tls: true
      authelia_smtp_from: "{{ common_smtp_from }}"
      authelia_jwt_token: "{{ vault_jwt_token }}"
      authelia_session_token: "{{ vault_session_token }}"
      authelia_smtp_username: "{{ vault_smtp_username }}"
      authelia_smtp_password: "{{ vault_smtp_password }}"
      authelia_admin_username: "{{ vault_admin_username }}"
      authelia_admin_password: "{{ vault_admin_password }}"
      authelia_admin_email: "{{ vault_admin_email }}"
      authelia_admin_display_name: "{{ vault_admin_username }}"
      authelia_install_path: "{{ common_install_root }}/authelia"

    # https://hub.docker.com/r/crazymax/fail2ban/tags
    - role: fail2ban
      fail2ban_image_tag: 0.11.2
      fail2ban_log_path: "{{ common_logs_root }}/fail2ban"
      fail2ban_data_path: "{{ common_data_root }}/fail2ban"
      fail2ban_ingest_path: "{{ common_logs_root }}"
      fail2ban_smtp_server: "{{ common_smtp_server }}"
      fail2ban_smtp_domain: "{{ vault_domain }}"
      fail2ban_smtp_username: "{{ vault_smtp_username }}"
      fail2ban_smtp_password: "{{ vault_smtp_password }}"
      fail2ban_admin_email: "{{ vault_smtp_username }}"
      fail2ban_smtp_sender: "{{ common_smtp_from }}"
      fail2ban_install_path: "{{ common_install_root }}/fail2ban"
