---
- name: Install User Services
  hosts: all
  vars_files:
    - ../vars/common.yml
    - ../vars/secrets
    - ../config/versions.yml
  become: true
  gather_facts: true

  pre_tasks:
    - name: Update apt cache if needed
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 86400

  post_tasks:
    - name: Cleanup old images
      ansible.builtin.command:
        cmd: "docker image prune -a --force"
      register: this
      changed_when: "'Deleted Images' in this.stdout"

  roles:
    - role: docker
      docker_networks:
        - "{{ common_traefik_network_name }}"
        - "{{ common_pusher_network_name }}"

    - role: containers/bitwarden
      bitwarden_config_path: "{{ common_data_root }}/bitwarden"
      bitwarden_install_path: "{{ common_install_root }}/bitwarden"
      bitwarden_logs_path: "{{ common_logs_root }}/bitwarden"

    - role: containers/pwpusher
      pwpusher_install_path: "{{ common_install_root }}/pwpusher"
