---
targets:
  - src: install
    dest: "{{ common_install_root }}/fail2ban"
  - dest: "{{ common_data_root }}/fail2ban"
  - dest: "{{ common_logs_root }}/fail2ban"

permissions:
  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0550'
    paths:
      - install
      - install/*

  - owner: root
    group: root
    mode: '0440'
    dir_mode: '0750'
    paths:
      - "{{ common_data_root }}/fail2ban"
      - "{{ common_logs_root }}/fail2ban"
