---
- name: Install media management services
  hosts: all
  vars_files:
    - ../../vars/secrets.yml
  become: true
  gather_facts: false
  roles:
    # https://github.com/linuxserver/docker-sonarr/releases
    - role: arr
      arr_service_name: sonarr
      arr_image_tag: 2.0.0.5344-ls82
      arr_fqdn: shows.{{ vault_domain }}
      arr_expose_port: 8989
      arr_install_path: /opt/sonarr
      arr_data_path: /{{ vault_stack_name }}/sonarr
      arr_downloads_path: /{{ vault_stack_name }}/downloads
      arr_media_root: /mnt/media

    # https://github.com/linuxserver/docker-radarr/releases
    - role: arr
      arr_service_name: radarr
      arr_image_tag: v0.2.0.1504-ls79
      arr_fqdn: movies.{{ vault_domain }}
      arr_expose_port: 7878
      arr_install_path: /opt/radarr
      arr_data_path: /{{ vault_stack_name }}/radarr
      arr_downloads_path: /{{ vault_stack_name }}/downloads
      arr_media_root: /mnt/media

    # https://github.com/linuxserver/docker-lidarr/releases
    - role: arr
      arr_service_name: lidarr
      arr_image_tag: 0.7.1.1381-ls19
      arr_fqdn: music.{{ vault_domain }}
      arr_expose_port: 8686
      arr_install_path: /opt/lidarr
      arr_data_path: /{{ vault_stack_name }}/lidarr
      arr_downloads_path: /{{ vault_stack_name }}/downloads
      arr_media_root: /mnt/media
