---
- name: Install media management services
  hosts: all
  vars_files:
    - ../../vars/common.yml
    - ../../vars/secrets.yml
  become: true
  gather_facts: false

  roles:
    # https://github.com/linuxserver/docker-sonarr/releases
    - role: arr
      arr_service_name: sonarr
      arr_image_tag: 3.0.6.1265-ls113
      arr_fqdn: shows.{{ vault_domain }}
      arr_expose_port: 8989
      arr_install_path: "{{ common_install_root }}/sonarr"
      arr_data_path: /{{ vault_stack_name }}/sonarr
      arr_downloads_path: /downloads
      arr_media_root: /mnt/media
      arr_user: "{{ common_downloads_user }}"
      arr_group: "{{ common_downloads_group }}"

    # https://github.com/linuxserver/docker-radarr/releases
    - role: arr
      arr_service_name: radarr
      arr_image_tag: 3.2.2.5080-ls109
      arr_fqdn: movies.{{ vault_domain }}
      arr_expose_port: 7878
      arr_install_path: "{{ common_install_root }}/radarr"
      arr_data_path: /{{ vault_stack_name }}/radarr
      arr_downloads_path: /downloads
      arr_media_root: /mnt/media
      arr_user: "{{ common_downloads_user }}"
      arr_group: "{{ common_downloads_group }}"

    # https://github.com/linuxserver/docker-lidarr/releases
    - role: arr
      arr_service_name: lidarr
      arr_image_tag: 0.8.1.2135-ls53
      arr_fqdn: music.{{ vault_domain }}
      arr_expose_port: 8686
      arr_install_path: "{{ common_install_root }}/lidarr"
      arr_data_path: /{{ vault_stack_name }}/lidarr
      arr_downloads_path: /downloads
      arr_media_root: /mnt/media
      arr_user: "{{ common_downloads_user }}"
      arr_group: "{{ common_downloads_group }}"
