---
- name: Add group {{ nzbget_group }}
  group:
    name: "{{ nzbget_group }}"
    state: present

- name: Add user {{ nzbget_user }}
  user:
    name: "{{ nzbget_user }}"
    group: "{{ nzbget_group }}"
    shell: /sbin/nologin
    create_home: false
    append: false
    state: present

- name: Export group id
  getent:
    database: group
    key: "{{ nzbget_group }}"

- name: Export user id
  getent:
    database: passwd
    key: "{{ nzbget_user }}"

- name: Gather created username and group IDs
  set_fact:
    nzbget_user_id: "{{ getent_passwd[nzbget_user][1] }}"
    nzbget_group_id: "{{ getent_group[nzbget_group][1] }}"
