---
- name: Reload systemd
  ansible.builtin.systemd:
    daemon_reload: true

- name: Enable timer
  ansible.builtin.systemd:
    name: "restic-{{ restic_schedule_name }}.timer"
    state: started
    enabled: true
