---
- name: Ensure postfix install directory
  file:
    path: "{{ postfix_install_path }}"
    owner: root
    group: root
    mode: 0440
    state: directory

- name: Install postfix files
  copy:
    src: docker-compose.yml
    dest: "{{ postfix_install_path }}/docker-compose.yml"
    owner: root
    group: root
    mode: 0440
  notify:
    - restart postfix

- name: Copying template files
  template:
    src: .env.j2
    dest: "{{ postfix_install_path }}/.env"
    owner: root
    group: root
    mode: 0440
  notify:
    - restart postfix

- name: Check for latest
  command:
    cmd: echo 'pull latest docker image'
  when: postfix_image_tag == 'latest'
  notify: restart postfix

- name: Check if running
  command:
    cmd: docker ps -qf name="postfix"
  register: this
  changed_when: not this.stdout
  failed_when: false
  notify: restart postfix
